name: hylas
favicon: null
layout_spectrum: 0.24881751043722034
typography_spectrum: 0.10514691029675305
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.5
  lightness: 0.8716364330612123
  saturation: 0.6192360308486968
  rhythmicContrast: 1
purpose: []
